//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiWell.Payment
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BiWellEntities : DbContext
    {
        public BiWellEntities()
            : base("name=BiWellEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ItemWeight> ItemWeights { get; set; }
        public virtual DbSet<log_message_type> log_message_type { get; set; }
        public virtual DbSet<log_record> log_record { get; set; }
        public virtual DbSet<log_source> log_source { get; set; }
        public virtual DbSet<order_payment> order_payment { get; set; }
    }
}
