//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiWell.Payment
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemWeight
    {
        public string ItemId { get; set; }
        public decimal Weight { get; set; }
        public string Name { get; set; }
    }
}
