//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiWell.Payment
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_record
    {
        public int id { get; set; }
        public string message { get; set; }
        public int message_type_id { get; set; }
        public int source_id { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual log_message_type log_message_type { get; set; }
        public virtual log_source log_source { get; set; }
    }
}
